program ZenSystem;

uses
  Vcl.Forms,
  FWelcome in 'FWelcome.pas' {frmWelcome},
  FMain in 'FMain.pas' {frmMain},
  uHTTP in 'uses\uHTTP.pas',
  XSuperJSON in 'uses\XSuperJSON.pas',
  XSuperObject in 'uses\XSuperObject.pas',
  FdmDB in 'uses\FdmDB.pas' {dmDB: TDataModule},
  MainSource in 'uses\MainSource.pas',
  FConfigSetup in 'uses\FConfigSetup.pas' {frmConfigSetup},
  FLogin in 'appconfig\FLogin.pas' {frmLogin},
  FPassword in 'appconfig\FPassword.pas' {frmPassword},
  FGroupManagement in 'appconfig\FGroupManagement.pas' {frmGroupManagement},
  FGroupAccessAdd in 'appconfig\FGroupAccessAdd.pas' {frmGroupAccessAdd},
  FUserManagement in 'appconfig\FUserManagement.pas' {frmUserManagement},
  Vcl.Themes,
  Vcl.Styles,
  FMasterDivisi in 'Hrd\FMasterDivisi.pas' {frmMasterDivisi},
  FMasterKaryawan in 'Hrd\FMasterKaryawan.pas' {frmMasterKaryawan},
  FMasterKaryawanAdd in 'Hrd\FMasterKaryawanAdd.pas' {frmMasterKaryawanAdd},
  FKaryawanOld in 'Hrd\FKaryawanOld.pas' {frmKaryawanOld},
  FKontrakKerjaUpdate in 'Hrd\FKontrakKerjaUpdate.pas' {frmKontrakKerjaUpdate},
  FSaldoCuti in 'Hrd\FSaldoCuti.pas' {frmSaldoCuti},
  FIjinCuti in 'Hrd\FIjinCuti.pas' {frmIjinCuti},
  FIjinCutiCetak in 'Hrd\FIjinCutiCetak.pas' {frmIjinCutiCetak},
  FIjinCutiList in 'Hrd\FIjinCutiList.pas' {frmIjinCutiList},
  FlemburCetak in 'Hrd\FlemburCetak.pas' {frmLemburCetak},
  FlemburInput in 'Hrd\FlemburInput.pas' {frmLemburInput},
  FLemburList in 'Hrd\FLemburList.pas' {frmLemburList},
  FIjinLainCetak in 'Hrd\FIjinLainCetak.pas' {frmIjinLainCetak},
  FIjinTidakMasukInput in 'Hrd\FIjinTidakMasukInput.pas' {frmIjinTidakMasukInput},
  FIjinTMList in 'Hrd\FIjinTMList.pas' {frmIjinTMList},
  FIjinTidakMasuk in 'Hrd\FIjinTidakMasuk.pas' {frmIjinTidakMasuk},
  FRekapHarian in 'Hrd\FRekapHarian.pas' {frmRekapHarian},
  FRekapSelectFp in 'Hrd\FRekapSelectFp.pas' {frmRekapSelectFP},
  FPayrollPotongan in 'Hrd\FPayrollPotongan.pas' {frmPayrollPotongan},
  FPayrollTambahan in 'Hrd\FPayrollTambahan.pas' {frmPayrollTambahan},
  FHistoryKontrak in 'Hrd\FHistoryKontrak.pas' {frmHistoryKontrak},
  FPayrollCashInBali in 'Hrd\FPayrollCashInBali.pas' {frmPayrollCashInBali},
  FIjinKeluar in 'Hrd\FIjinKeluar.pas' {frmIjinKeluar},
  FIjinTidakMasukList in 'Hrd\FIjinTidakMasukList.pas' {frmIjinTidakMasukList},
  FSakitInput in 'Hrd\FSakitInput.pas' {frmSakitInput},
  FRekapHarianNew in 'Hrd\FRekapHarianNew.pas' {frmRekapHarianNew},
  FPayrollCashIn in 'Hrd\FPayrollCashIn.pas' {frmPayrollCashIn},
  FRekapHarianBali in 'Hrd\FRekapHarianBali.pas' {frmRekapHarianBali},
  FPayrollAdminBali in 'Hrd\FPayrollAdminBali.pas' {frmPayrollAdminBali},
  FPayrollPotonganBali in 'Hrd\FPayrollPotonganBali.pas' {frmPayrollPotonganBali},
  FPayrollTambahanBali in 'Hrd\FPayrollTambahanBali.pas' {frmPayrollTambahanBali},
  FRekapHarianBaru in 'Hrd\FRekapHarianBaru.pas' {frmRekapHarianBaru},
  FKaryawanScanFinger in 'FpSrc\FKaryawanScanFinger.pas' {frmKaryawanScanFinger},
  FNotes in 'FpSrc\FNotes.pas' {frmNotes},
  FRegKaryawan in 'FpSrc\FRegKaryawan.pas' {frmRegKaryawan},
  FMasterKontrak in 'Hrd\FMasterKontrak.pas' {frmMasterKontrak},
  FMasterKontrakAdd in 'Hrd\FMasterKontrakAdd.pas' {frmMasterKontrakAdd},
  FKontrakKerjaDetails in 'Hrd\FKontrakKerjaDetails.pas' {frmKontrakKerjaDetails},
  FSaldoCutiGenerate in 'Hrd\FSaldoCutiGenerate.pas' {frmSaldoCutiGenerate},
  FIjinLainList in 'Hrd\FIjinLainList.pas' {frmIjinLainList},
  FIjinLainInput in 'Hrd\FIjinLainInput.pas' {frmIjinLainInput},
  FIjinSakitInput in 'Hrd\FIjinSakitInput.pas' {frmIjinSakitInput},
  FIjinSakitList in 'Hrd\FIjinSakitList.pas' {frmIjinSakitList},
  FIjinMasukInput in 'Hrd\FIjinMasukInput.pas' {frmIjinMasukInput},
  FIjinMasukList in 'Hrd\FIjinMasukList.pas' {frmIjinMasukList},
  FIjinPulangList in 'Hrd\FIjinPulangList.pas' {frmIjinPulangList},
  FIjinPulangInput in 'Hrd\FIjinPulangInput.pas' {frmIjinPulangInput},
  FPos in 'pos\FPos.pas' {frmPos},
  FMenuTrans in 'pos\FMenuTrans.pas' {frmMenuTrans},
  FBrowseTrans in 'pos\FBrowseTrans.pas' {frmBrowseTrans},
  FBuyAdditional in 'pos\FBuyAdditional.pas' {frmBuyAdditional},
  FPrintSO in 'pos\FPrintSO.pas' {frmPintSO},
  FChangeTR in 'pos\FChangeTR.pas' {frmChangeTR},
  FChangeRoom in 'pos\FChangeRoom.pas' {frmChangeRoom},
  FPelunasan in 'pos\FPelunasan.pas' {frmPelunasan},
  FPayment in 'pos\FPayment.pas' {frmPayment},
  FBuyGC in 'pos\FBuyGC.pas' {frmBuyGC},
  FTransRedeem in 'pos\FTransRedeem.pas' {frmTransRedeem},
  FPrintRedeem in 'pos\FPrintRedeem.pas' {frmPrintRedeem},
  FPrintProduk in 'pos\FPrintProduk.pas' {frmPrintProduk},
  FLogo in 'appconfig\FLogo.pas' {frmLogo},
  FMerger in 'pos\FMerger.pas' {frmMerger},
  FPayGC in 'pos\FPayGC.pas' {frmPayGC},
  FTransMember in 'pos\FTransMember.pas' {frmTransMember},
  FNewPrintTrans in 'pos\FNewPrintTrans.pas' {frmNewPrintTrans},
  FNewMenuTrans in 'pos\FNewMenuTrans.pas' {frmNewMenuTrans},
  FSelectTherapist in 'pos\FSelectTherapist.pas' {frmSelectTherapist},
  ORI_FPosMainMenu in 'pos\master\ORI_FPosMainMenu.pas' {ORI_frmPosMainMenu},
  FPosMainMenuInput in 'pos\master\FPosMainMenuInput.pas' {frmPosMainMenuInput},
  FPosTransHotel in 'pos\FPosTransHotel.pas' {frmPosTransHotel},
  FBuyProduct in 'pos\FBuyProduct.pas' {frmBuyProduct},
  FPaketGC in 'pos\master\FPaketGC.pas' {frmPaketGC},
  FSelectGC in 'pos\master\FSelectGC.pas' {frmSelectGC},
  FGiftCertificate in 'pos\master\FGiftCertificate.pas' {frmGiftCertificate},
  FGiftCertificateMaster in 'pos\master\FGiftCertificateMaster.pas' {frmGiftCertificateMaster},
  FPaketGCInput in 'pos\master\FPaketGCInput.pas' {frmPaketGCInput},
  FPosReleaseLock in 'pos\FPosReleaseLock.pas' {frmPosReleaseLock},
  FPosPembayaran in 'pos\FPosPembayaran.pas' {frmPosPembayaran},
  FPosPromoMaster in 'pos\master\FPosPromoMaster.pas' {frmPosPromoMaster},
  FPosPembayaranSelect in 'pos\FPosPembayaranSelect.pas' {frmPosPembayaranSelect},
  FMasterPassword in 'appconfig\FMasterPassword.pas' {frmMasterPassword},
  FPosPembayaranDisc in 'pos\FPosPembayaranDisc.pas' {frmPosPembayaranDisc},
  FPosPembayaranPay in 'pos\FPosPembayaranPay.pas' {frmPosPembayaranPay},
  FPosMasterPayment in 'pos\master\FPosMasterPayment.pas' {frmPosMasterPayment},
  FMasterBank in 'kasbank\FMasterBank.pas' {frmMasterBank},
  FMasterBankAdd in 'kasbank\FMasterBankAdd.pas' {frmMasterBankAdd},
  FReportGCMaster in 'Report\PosReport\FReportGCMaster.pas' {frmReportGCMaster},
  FPrintTrans in 'pos\FPrintTrans.pas' {frmPrintTrans},
  FMemberCari in 'pos\master\FMemberCari.pas' {frmMemberCari},
  FMemberMaster in 'pos\master\FMemberMaster.pas' {frmMemberMaster},
  FMemberMasterAdd in 'pos\master\FMemberMasterAdd.pas' {frmMemberMasterAdd},
  FReportPendapatanBulanan in 'Report\PosReport\FReportPendapatanBulanan.pas' {frmReportPendapatanBulanan},
  FReportPosPayment in 'Report\PosReport\FReportPosPayment.pas' {frmReportPosPayment},
  FReportPosMaster in 'Report\PosReport\FReportPosMaster.pas' {frmReportPoSMaster},
  FTherapisCall2 in 'pos\FTherapisCall2.pas' {frmTherapisCall2},
  FMasterReportVariable in 'Hrd\FMasterReportVariable.pas' {frmMasterReportVariable},
  FReportPeriode in 'Hrd\FReportPeriode.pas' {frmReportPeriode},
  FPayrollPeriode in 'Hrd\FPayrollPeriode.pas' {frmPayrollPeriode},
  FTherapistReport in 'Hrd\FTherapistReport.pas' {frmTherapistReport},
  FTherapisStart in 'pos\FTherapisStart.pas' {frmTherapisStart},
  FTherapistStatus in 'pos\FTherapistStatus.pas' {frmTherapistStatus},
  FTherapisCall in 'pos\FTherapisCall.pas' {frmTherapisCall},
  FLaporanTherapistReport in 'Hrd\FLaporanTherapistReport.pas' {frmLaporanTherapistReport},
  FBALIReportPendapatanHarian in 'Report\PosReport\FBALIReportPendapatanHarian.pas' {frmBALIReportPendapatanHarian},
  FReejectGuest in 'pos\FReejectGuest.pas' {frmRejectGuest},
  FPosTransMain in 'pos\FPosTransMain.pas' {frmPosTransMain},
  FPosTransMainDetails in 'pos\FPosTransMainDetails.pas' {frmPosTransMainDetails},
  FMemberHistory in 'pos\FMemberHistory.pas' {frmMemberHistory},
  FRepTopRequest in 'Report\PosReport\FRepTopRequest.pas' {frmRepTopRequest},
  FTHRCutOff in 'Hrd\FTHRCutOff.pas' {frmTHRCutOff},
  FRekapHarianOld in 'Hrd\FRekapHarianOld.pas' {frmRekapHarianOld},
  FMasterShift in 'Hrd\FMasterShift.pas' {frmMasterShift},
  FMasterShiftAdd in 'Hrd\FMasterShiftAdd.pas' {frmMasterShiftAdd},
  FPayrollAdmin in 'Hrd\FPayrollAdmin.pas' {frmPayrollAdmin},
  FJadwalAll in 'Hrd\FJadwalAll.pas' {frmJadwalAll},
  FJadwalOutlet in 'Hrd\FJadwalOutlet.pas' {frmJadwalOutlet},
  FJadwalOutletAdd in 'Hrd\FJadwalOutletAdd.pas' {frmJadwalOutletAdd},
  FJadwalOutletChange in 'Hrd\FJadwalOutletChange.pas' {frmJadwalOutletChange},
  FJadwalTetap in 'Hrd\FJadwalTetap.pas' {frmJadwalTetap},
  FJadwalTetapAdd in 'Hrd\FJadwalTetapAdd.pas' {frmJadwalTetapAdd},
  FRepPotongan in 'Hrd\FRepPotongan.pas' {frmRepPotongan},
  FReportPayroll in 'Hrd\FReportPayroll.pas' {frmReportPayroll},
  FReportKontrakBerjalan in 'Hrd\FReportKontrakBerjalan.pas' {frmReportKontrakBerjalan},
  FRepTambahan in 'Hrd\FRepTambahan.pas' {frmRepTambahan},
  FRepPayrollDetails in 'Hrd\FRepPayrollDetails.pas' {frmRepPayrollDetails},
  FReportOtherPayroll in 'Hrd\FReportOtherPayroll.pas' {frmReportOtherPayroll},
  FCetakKomisi in 'Hrd\FCetakKomisi.pas' {frmCetakKomisi},
  FCetakPayroll in 'Hrd\FCetakPayroll.pas' {frmCetakPayroll},
  FReportCashIn in 'Hrd\FReportCashIn.pas' {frmReportCashIn},
  FReportSakit in 'Hrd\FReportSakit.pas' {frmReportSakit},
  FReportAbsenManual in 'Hrd\FReportAbsenManual.pas' {frmReportAbsenManual},
  FReportRekapAbsen in 'Hrd\FReportRekapAbsen.pas' {frmLapRekapAbsen},
  FReportLembur in 'Hrd\FReportLembur.pas' {frmReportLembur},
  FReportCuti in 'Hrd\FReportCuti.pas' {frmReportCuti},
  FReportVoid in 'Report\PosReport\FReportVoid.pas' {frmReportVoid},
  FReportDayli in 'Report\PosReport\FReportDayli.pas' {frmReportDayli},
  FLiburNasional in 'Hrd\FLiburNasional.pas' {frmLiburNasional},
  FRegistrationDrivers in 'pos\FRegistrationDrivers.pas' {frmRegistrationDrivers},
  FDrivers in 'pos\FDrivers.pas' {frmDrivers},
  FTHRPerhitungan in 'Hrd\FTHRPerhitungan.pas' {frmTHRPerhitungan},
  FTHRParameter in 'Hrd\FTHRParameter.pas' {frmTHRParameter},
  FTHRReport in 'Hrd\FTHRReport.pas' {frmTHRReport},
  FDriverSelectTrans in 'pos\FDriverSelectTrans.pas' {frmDriverSelectTrans},
  FPrintDriversTrans in 'pos\FPrintDriversTrans.pas' {frmPintDriversTrans},
  FEmpty in 'appconfig\FEmpty.pas' {frmEmpty},
  FTestMemoryTable in 'TestForm\FTestMemoryTable.pas' {frmTestMemoryTable},
  FPosTransPaymentTips in 'pos\FPosTransPaymentTips.pas' {frmPosTransPaymentTips},
  FPosLapTips in 'pos\FPosLapTips.pas' {frmPosLapTips},
  FChangeJadwal in 'Hrd\FChangeJadwal.pas' {frmChangeJadwal},
  FReportSchedule in 'Hrd\FReportSchedule.pas' {frmReportSchedule},
  FReportPendapatanHarian in 'Report\PosReport\FReportPendapatanHarian.pas' {frmReportPendapatanHarian},
  FPrintRatingCode in 'pos\FPrintRatingCode.pas' {frmPrintRatingCode},
  FHOMasukBarang in 'product\FHOMasukBarang.pas' {frmHOMasukBarang},
  FPresensiManual in 'Hrd\FPresensiManual.pas' {frmPresensiManual},
  FPosMainMenu in 'pos\master\FPosMainMenu.pas' {frmPosMainMenu},
  FPeriodeUM in 'Hrd\FPeriodeUM.pas' {frmPeriodeUM};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Zen Internal System';
  Application.CreateForm(TdmDB, dmDB);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
